language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - cmake3
      env:
        - CC=gcc-7

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake3
      env:
        - CC=clang-4.0

    - os: osx
      compiler: clang
      osx_image: xcode9

before_script:
  - mkdir cmake-build-debug
    cd cmake-build-debug
    cmake .. -DCMAKE_BUILD_TYPE=Debug

script:
  - cd cmake-build-debug
    ./sb_test