#
# .travis.yml: Travis CI support
#
# This file is part of Sweet B, a safe, compact, embeddable elliptic curve
# cryptography library.
#
# Sweet B is provided under the terms of the included LICENSE file. All
# other rights are reserved.
#
# Copyright 2017 Wearable Inc.
#

language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      dist: trusty
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - cmake3
      env:
        - C_COMPILER=gcc-7

    - os: linux
      compiler: clang
      dist: trusty
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
          packages:
            - clang-4.0
            - cmake3
      env:
        - C_COMPILER=clang-4.0

    - os: osx
      compiler: clang
      osx_image: xcode9

before_script:
  - mkdir cmake-build-debug
  - cd cmake-build-debug
  - cmake .. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_C_COMPILER=$C_COMPILER

script:
  - make
  - ./sb_test